import Head from 'next/head'
import BlogHome from "./Components/Home";

export default function Home() {

    return (
        <>
            <div>
                <Head>
                    <title>Blog Web</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>
            </div>
            <BlogHome/>
        </>
    )
}
